#all the configuration and connection details for the system

#-----PostgreSQL connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin123
#admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bankingdb

#-----Hibernate configuration
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

#-----Mail
quarkus.mailer.from=YOUR_VERIFIED_SENDER_EMAIL
quarkus.mailer.host=smtp.sendgrid.net
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=apikey
quarkus.mailer.password=${SENDGRID_API_KEY}

quarkus.log.category."io.quarkus.mailer".level=DEBUG
quarkus.log.category."io.vertx.ext.mail".level=DEBUG
quarkus.log.category."io.netty.handler.ssl".level=DEBUG

#-----Reminder configuration
deprecated.reminder.enabled=true
deprecated.reminder.sla-info-days=14
deprecated.reminder.sla-minor-days=10
deprecated.reminder.sla-major-days=7
deprecated.reminder.sla-critical-days=3

deprecated.reminder.sync-cron=0 0 9 * * ?
deprecated.reminder.email-cron=0 15 9 * * ?

deprecated.reminder.default-recipients=purajan01@gmail.com

#-----OpenAPI configuration
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
#quarkus.smallrye-openapi.info=Banking API
#quarkus.smallrye-openapi.version=1.0.0
#quarkus.smallrye-openapi.description=API for managing banking operations

#-----CORS configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:8080
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type, Authorization

#-----dev
#quarkus.profile=dev
#%dev.quarkus.datasource.devservices.image-name=postgres:13.3
#%dev.quarkus.datasource.devservices.port=5432
%dev.quarkus.hibernate-orm.log.sql=true

#-----JWT validation configuration
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=com.bank
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.http.auth.proactive=false
#mp.jwt.verify.audience=banking-system
#quarkus.smallrye-jwt.enabled=true

#-----scheduler configuration
quarkus.scheduler.enabled=true
quarkus.scheduler.start-mode=normal

#-----sonar details
sonar.url=https://sonarcloud.io
sonar.organization=alessaest
sonar.project-key=alessaest_banking-system
#204d807764796ffc28cf71c088359a8882f9db1e
sonar.token=${SONAR_TOKEN}
sonar.rules=java:S1133
sonar.severities=INFO
sonar.types=CODE_SMELL,BUG,VULNERABILITY
